input {
    touchdevice {
        enabled = true
        output = eDP-1
    }
}

decoration {
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}

general {
    col.active_border = rgba(d9514eee) rgba(8f2f2dee) 45deg
    col.inactive_border = rgba(3a2422aa)
}
